ALTER TABLE facebook_posts
  ADD COLUMN IF NOT EXISTS likes_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS comments_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS shares_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS metrics_last_synced_at TIMESTAMP;

ALTER TABLE linkedin_posts
  ADD COLUMN IF NOT EXISTS likes_count INTEGER,
  ADD COLUMN IF NOT EXISTS comments_count INTEGER,
  ADD COLUMN IF NOT EXISTS shares_count INTEGER,
  ADD COLUMN IF NOT EXISTS metrics_last_synced_at TIMESTAMP,
  ADD COLUMN IF NOT EXISTS metrics_error TEXT;
